/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ldfhq7feovhepbjaivc4jrmjku.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4rskfhhw4nggdc7bwp65q3wtre",
    "aws_cognito_identity_pool_id": "us-east-1:598fd625-c497-4619-83e6-737c536eeaab",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4xtNoKmPw",
    "aws_user_pools_web_client_id": "5m0annb1c18d24vcmuthj0n1qa",
    "oauth": {}
};


export default awsmobile;
